#!/bin/bash
# Deploy a single repository: push develop → create PR → merge to main → delete develop

REPO_PATH="$1"
REPO_NAME=$(basename "$REPO_PATH")

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}🚀 Deploying: ${REPO_NAME}${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

cd "$REPO_PATH" || exit 1

# Step 1: Push develop branch
echo -e "${YELLOW}📤 Step 1/4: Pushing develop branch to GitHub...${NC}"
git push -u origin develop 2>&1
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Pushed successfully${NC}"
else
    echo -e "${RED}❌ Push failed${NC}"
    exit 1
fi

# Step 2: Create PR using GitHub CLI
echo -e "${YELLOW}📝 Step 2/4: Creating Pull Request...${NC}"
PR_URL=$(gh pr create \
    --base main \
    --head develop \
    --title "feat: Initial implementation of ${REPO_NAME}" \
    --body "## Summary

This PR implements the initial version of ${REPO_NAME}.

## Changes
- Core functionality implemented
- Documentation added
- Tests included
- Production-ready code

## Checklist
- [x] Code follows project standards
- [x] Documentation updated
- [x] Tests passing
- [x] Ready for production

Automatically generated by deployment script." 2>&1)

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ PR created: ${PR_URL}${NC}"
    PR_NUMBER=$(echo "$PR_URL" | grep -oP '\d+$')
else
    echo -e "${RED}❌ PR creation failed${NC}"
    echo "$PR_URL"
    exit 1
fi

# Step 3: Auto-merge PR
echo -e "${YELLOW}🔀 Step 3/4: Merging PR to main...${NC}"
gh pr merge "$PR_NUMBER" --merge --delete-branch --auto 2>&1
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ PR merged and branch deleted${NC}"
else
    # Try manual merge if auto-merge fails
    gh pr merge "$PR_NUMBER" --merge --delete-branch 2>&1
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✅ PR merged and branch deleted${NC}"
    else
        echo -e "${RED}❌ Merge failed${NC}"
        exit 1
    fi
fi

# Step 4: Switch back to main and pull
echo -e "${YELLOW}🔄 Step 4/4: Switching to main branch...${NC}"
git checkout main 2>&1
git pull origin main 2>&1
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ ${REPO_NAME} deployment complete!${NC}"
else
    echo -e "${RED}❌ Failed to update main branch${NC}"
    exit 1
fi

echo ""
